# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9f11794e03638029ec304433e5c5032b0333b5b04c9d6248f35783996aaea32e7ac76d687c2194c830a6e8ef8965f0cee0c610f92d6c0ade8069e5501382960

test:
  secret_key_base: 07ef9beaba10978a109b298584879a66844c73ff87abbb2ee0952372618e409bbb2c5ab2e470f1b41352e98c50c2b31f8cc82153752ec0e3fe99e067c0ab3c7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
